include:
  - services/transmission/transmission.yml

networks:
  pi-net:
    name: "pi-net"
    driver: "bridge"
    ipam:
      config:
        - subnet: "172.19.1.0/24"
          gateway: "172.19.1.1"